### ISSUE TITLE
wrong token order for parenthesis

### ISSUE THREAD

**Issue by PaulicStudios** [JonasGoetz01/42-minishell#283]
```
/workspaces/42-minishell ❯ (echo 1 && echo 2) | cat -e
Tokens:
Type: 1, Value: (
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 1
Type: 15, Value:  
Type: 10, Value: &&
Type: 15, Value:  
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 2
Type: 2, Value: )
Type: 15, Value:  
Type: 8, Value: |
Type: 15, Value:  
Type: 0, Value: cat
Type: 15, Value:  
Type: 0, Value: -e
Tokens:
Type: 1, Value: (
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 1
Type: 15, Value:  
Type: 10, Value: &&
Type: 15, Value:  
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 2
Type: 2, Value: )
Type: 15, Value:  
Type: 8, Value: |
Type: 15, Value:  
Type: 0, Value: cat
Type: 15, Value:  
Type: 0, Value: -e
Tokens:
Type: 1, Value: (
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 1
Type: 15, Value:  
Type: 10, Value: &&
Type: 15, Value:  
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 2
Type: 2, Value: )
Type: 15, Value:  
Type: 8, Value: |
Type: 15, Value:  
Type: 0, Value: cat
Type: 15, Value:  
Type: 0, Value: -e
Tokens:
Type: 1, Value: (
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 1
Type: 15, Value:  
Type: 10, Value: &&
Type: 15, Value:  
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 2
Type: 2, Value: )
Type: 15, Value:  
Type: 8, Value: |
Type: 15, Value:  
Type: 0, Value: cat
Type: 15, Value:  
Type: 0, Value: -e
Input is valid
Highest token: &&
Highest Bracket Level: 1
Highest token: 1
Highest Bracket Level: 1
Highest token: |
Highest Bracket Level: -1
Highest token: 2
Highest Bracket Level: 0
Highest token: -e
Highest Bracket Level: 0
        Type: 15, Value:   Prio: -1
        Type: 0, Value: cat Prio: -1
        Type: 15, Value:   Prio: -1
        Type: 0, Value: -e Prio: -1
    Type: 8, Value: | Prio: 3
        Type: 15, Value:   Prio: -1
        Type: 0, Value: echo Prio: -1
        Type: 15, Value:   Prio: -1
        Type: 0, Value: 2 Prio: -1
        Type: 2, Value: ) Prio: -1
        Type: 15, Value:   Prio: -1
Type: 10, Value: && Prio: 4
    Type: 0, Value: echo Prio: 1
    Type: 15, Value:   Prio: 1
    Type: 0, Value: 1 Prio: 1
    Type: 15, Value:   Prio: 1
-----
        Type: 15, Value:   Prio: -1
        Type: 13, Value: cat Prio: -1
        Type: 15, Value:   Prio: -1
        Type: 14, Value: -e Prio: -1
    Type: 8, Value: | Prio: 3
        Type: 15, Value:   Prio: -1
        Type: 13, Value: echo Prio: -1
        Type: 15, Value:   Prio: -1
        Type: 14, Value: 2 Prio: -1
        Type: 2, Value: ) Prio: -1
        Type: 15, Value:   Prio: -1
Type: 10, Value: && Prio: 4
    Type: 13, Value: echo Prio: -1
    Type: 15, Value:   Prio: -1
    Type: 14, Value: 1 Prio: -1
    Type: 15, Value:   Prio: -1
```
